### PR TITLE
Add frame counter

### PR DESCRIPTION
**Pull request by Persson-dev**
I added a frame counter which counts the average render time of the last 60 frames and return the average frames per second. It can show the performance of an application if the frame rate is not limited.

### CODE REVIEW

**Comment by ucacaxm** [comment]
Hi Simon,

Thank you for the contribution.

Instead of moving each frame time in the array.
```
for(int i = 0; i < 60 - 1; i++)
    {
        m_frameTime[i] = m_frameTime[i + 1];
        frameSum += m_frameTime[i];
    }
```

it should be more efficient to do a circular array without any loop, something like this 


```
void Grapic::updateFrameCounter()
{
    static unsigned int lastTime = SDL_GetTicks();              // should be var of the class
    static int first = 0;                                                          // should be a var of the class
    static float frameSum = 1.f;                                           // should be a var of the class
    const unsigned int currentTime ;

    currentTime = SDL_GetTicks();                                    // get current time
    frameSum -= m_frameTime[ first ];                           // remove oldest frame time
    m_frameTime[ first ] = currentTime - lastTime;         // add new frame time to the array
    frameSum += m_frameTime[ first ];                           // add new frame time to the sum
    first = (first+1)%60;                                                    // move the circular array 
    m_averageFramePerSecond = 1.0 / ((float) frameSum / 60.0 * 0.001f);        // recompute frame rate
    lastTime = currentTime;                                              // save last time in lastTime
}
```

If you want to test please ? and I'll merge your pull.

Thanks a lot

**Comment by Persson-dev** [comment]
I tested both functions and they seem to work. Do I need to do something to update the doc of the website ?

**Comment by ucacaxm** [comment]
It would be nice to see your function appear in one of the tutorials ...

**Comment by Persson-dev** [comment]
I changed the tuto1 program, now the animation is smoother than before.

**Pull request merged**
